#name: Deploy Application

on:
  push:
    branches: [ production ]

jobs:
  deploy-to-production:
    name: "Dickson's Azure Server: Deploying..."
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_SERVER_USER }}
          key: ${{ secrets.AZURE_SERVER_KEY }}
          script: |
            cd ${{ secrets.AZURE_SERVER_APP_PATH }}
            chmod +x ./server-deploy.sh
            ./server-deploy.sh